version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"  # HDFS Namenode Web UI
      - "8020:8020"  # HDFS Namenode RPC
      - "50070:50070"  # HDFS Namenode HTTP
    networks:
      - spark-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    networks:
      - spark-net

  master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark Master port
    networks:
      - spark-net

  worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
    networks:
      - spark-net

networks:
  spark-net:

volumes:
  hdfs-namenode:
  hdfs-datanode:
